import {
  preferredWindow,getShortWindow,getWeeklyWindow,getCurrentCycleHistory,calculatePacing,inferSessions,buildHeatmap,
  aggregateCycles,sessionPlanner,formatDurationMs,inferCycle
} from './core.js';
import { installHelpTooltips } from './help.js';
const $=id=>document.getElementById(id); let state={};
const fmtPct=v=>Number.isFinite(v)?`${v.toFixed(v<10?1:0)}%`:'—';
const fmtDate=ms=>Number.isFinite(ms)?new Date(ms).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
const fmtDur=ms=>formatDurationMs(ms);
function renderQuotaSummary(usage) {
  const holder = $('quotaSummary');
  holder.textContent = '';
  const shortWindow = getShortWindow(usage);
  const weeklyWindow = getWeeklyWindow(usage);
  const fallback = preferredWindow(usage);
  const windows = [shortWindow, weeklyWindow].filter(window => Number.isFinite(window?.remainingPercent));
  if (!windows.length && Number.isFinite(fallback?.remainingPercent)) windows.push(fallback);
  if (!windows.length) {
    holder.textContent = 'No quota windows returned.';
    return;
  }

  for (const window of windows) {
    const card = document.createElement('article');
    card.className = 'panel quota-card';
    const header = document.createElement('div');
    header.className = 'panel-head';
    const name = document.createElement('strong');
    const remaining = document.createElement('span');
    name.textContent = window.label;
    remaining.textContent = Math.round(window.remainingPercent) + '% remaining';
    header.append(name, remaining);
    const bar = document.createElement('div');
    bar.className = 'bar';
    const fill = document.createElement('div');
    fill.style.width = String(window.remainingPercent) + '%';
    bar.append(fill);
    const reset = document.createElement('div');
    reset.className = 'muted';
    reset.textContent = window.resetAt
      ? 'Resets ' + new Date(window.resetAt * 1000).toLocaleString() + ' · ' + fmtDur(window.resetAt * 1000 - Date.now())
      : 'Reset unavailable';
    card.append(header, bar, reset);
    holder.append(card);
  }
}
function getSettings(){const settings=state.settings||{},mode=settings.toolbarMode==='remaining'?'both':settings.toolbarMode;return {...settings,toolbarMode:['both','weekly','short','used','pace'].includes(mode)?mode:'both'}}
function statusText(p){return !p?.burn?'Collecting':p?.status==='too-fast'?'Too fast':p?.status==='underusing'?'Underusing':'On pace'}
function recommendation(w,p){if(!w||!p)return'Quota data is unavailable.';if(p.shortfallMs>0)return`At the current pace, Codex is projected to run out about ${fmtDur(p.shortfallMs)} before reset. Reduce usage to roughly ${p.safePerDay.toFixed(1)}%/day or accept an early cutoff.`;if(p.status==='underusing'&&p.cycle?.remainingMs<2*24*3600000)return`You have ${Math.round(w.remainingPercent)}% remaining relatively late in the cycle. You can increase usage without exceeding your configured target.`;if(p.burn?.perDay>0)return`Current pace looks sustainable. Estimated remaining at reset: ${Math.max(0,Math.round(p.predictedRemainingAtReset??w.remainingPercent))}%.`;return'Not enough observed quota movement yet to estimate burn rate. Safe daily budget is still calculated from remaining quota and time until reset.'}
function renderOverview(){const usage=state.usage,w=preferredWindow(usage),h=getCurrentCycleHistory(state.history||[],usage),s=getSettings();$('subtitle').textContent=usage?.planType?`${usage.planType} plan · last updated ${state.lastSuccessAt?new Date(state.lastSuccessAt).toLocaleTimeString():'—'}`:'No current quota snapshot';if(!w)return;const p=calculatePacing(w,h,{targetRemaining:s.targetRemaining,tolerance:s.paceTolerance});$('limitName').textContent=w.label;$('remaining').textContent=`${Math.round(w.remainingPercent)}%`;$('remainingBar').style.width=`${w.remainingPercent}%`;$('resetLine').textContent=w.resetAt?`Resets ${new Date(w.resetAt*1000).toLocaleString()} · ${fmtDur(w.resetAt*1000-Date.now())}`:'Reset unavailable';const health=w.remainingPercent<=10?'Critical':w.remainingPercent<=25?'Low':p?.status==='too-fast'?'At risk':'Healthy';$('healthPill').textContent=health;$('pacePill').textContent=p?statusText(p):'—';$('burn').textContent=p?.burn?`${p.burn.perDay.toFixed(1)}% / day`:'Learning…';$('safe').textContent=p?`${p.safePerDay.toFixed(1)}% / day`:'—';$('empty').textContent=p?.burn?(p.exhaustionAt?fmtDate(p.exhaustionAt):'Not projected'):'Need observed use';$('atReset').textContent=p?.burn&&Number.isFinite(p?.predictedRemainingAtReset)?`${Math.round(p.predictedRemainingAtReset)}%`:'Need observed use';if(p?.cycle){$('idealLine').style.left=`${p.cycle.elapsedFraction*100}%`;$('actualDot').style.left=`${w.usedPercent}%`;$('cycleElapsed').textContent=fmtPct(p.cycle.elapsedFraction*100)}$('cycleUsed').textContent=fmtPct(w.usedPercent);$('resetCredits').textContent=String(usage?.resetCredits?.filter(c=>c.status==='available').length||0);$('utilization').textContent=fmtPct(w.usedPercent);$('valueUtil').textContent=fmtPct(w.usedPercent);$('unusedCapacity').textContent=fmtPct(w.remainingPercent);$('recommendation').textContent=recommendation(w,p)}
function renderTable(holder, headings, rows){holder.textContent='';const add=(values,className='')=>{const row=document.createElement('div');row.className=`tr ${className}`.trim();for(const value of values){const cell=document.createElement('span');cell.textContent=String(value??'');row.append(cell)}holder.append(row)};add(headings,'header');rows.forEach(values=>add(values))}
function rangeHistory(){const days=Number($('range').value||30),cut=Date.now()-days*86400000;return(state.history||[]).filter(p=>p.t>=cut).sort((a,b)=>a.t-b.t)}
function drawChart(){const history=rangeHistory(),c=$('historyChart'),ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);if(history.length<2){$('historyEmpty').textContent=history.length?'Only one sample in this range.':'No history in this range.';return}$('historyEmpty').textContent='';const pad={l:32,r:8,t:12,b:24},iw=w-pad.l-pad.r,ih=h-pad.t-pad.b,minT=history[0].t,maxT=history.at(-1).t||minT+1,color=getComputedStyle(document.body).color;ctx.strokeStyle=color;ctx.fillStyle=color;ctx.globalAlpha=.12;for(const yv of[0,25,50,75,100]){const y=pad.t+ih*(1-yv/100);ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(pad.l+iw,y);ctx.stroke()}ctx.globalAlpha=.55;ctx.font='10px system-ui';ctx.textAlign='right';for(const yv of[0,25,50,75,100]){const y=pad.t+ih*(1-yv/100);ctx.fillText(`${yv}%`,pad.l-5,y+3)}ctx.globalAlpha=.95;ctx.lineWidth=2;ctx.beginPath();history.forEach((p,i)=>{const x=pad.l+(p.t-minT)/Math.max(1,maxT-minT)*iw,y=pad.t+ih*(1-p.remaining/100);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.globalAlpha=.55;ctx.textAlign='left';ctx.fillText(new Date(minT).toLocaleDateString(),pad.l,h-4);ctx.textAlign='right';ctx.fillText(new Date(maxT).toLocaleDateString(),w-pad.r,h-4)}
function renderHeat(){const heat=buildHeatmap(state.history||[],7),holder=$('heatmap');holder.textContent='';heat.buckets.forEach((v,i)=>{const el=document.createElement('i'),r=heat.max? v/heat.max:0,l=r<=0?0:r<=.25?1:r<=.5?2:r<=.75?3:4;el.className=`heat ${l?`l${l}`:''}`;const d=new Date(heat.startMs+i*3600000);el.title=`${d.toLocaleString()}: ${v.toFixed(2)}% quota used`;holder.append(el)})}
function renderCycles(){const cycles=aggregateCycles(state.history||[],state.resetEvents||[]),holder=$('cycleTable');$('cycleCount').textContent=`${cycles.length} observed`;renderTable(holder,['Cycle','Max used','End remaining','Samples'],cycles.slice(0,10).map(c=>[`${new Date(c.start).toLocaleDateString()} → ${c.resetAt?new Date(c.resetAt*1000).toLocaleDateString():'?'}`,`${Math.round(c.maxUsed)}%`,`${Math.round(c.endRemaining)}%`,c.samples]))}
function renderSessions(){const sessions=inferSessions(state.history||[]),holder=$('sessionsTable');$('sessionsCount').textContent=String(sessions.length);$('avgSessionBurn').textContent=sessions.length?`${(sessions.reduce((a,s)=>a+s.burned,0)/sessions.length).toFixed(1)}%`:'—';$('largestSession').textContent=sessions.length?`${Math.max(...sessions.map(s=>s.burned)).toFixed(1)}%`:'—';const hourBurn=Array(24).fill(0);sessions.forEach(s=>hourBurn[new Date(s.start).getHours()]+=s.burned);const peak=hourBurn.some(Boolean)?hourBurn.indexOf(Math.max(...hourBurn)):null;$('peakHour').textContent=peak==null?'—':`${String(peak).padStart(2,'0')}:00`;renderTable(holder,['Start','Duration','Quota used','Burn/hour'],sessions.slice().reverse().slice(0,20).map(s=>[new Date(s.start).toLocaleString(),fmtDur(s.durationMs),`${s.burned.toFixed(1)}%`,Number.isFinite(s.burnPerHour)?`${s.burnPerHour.toFixed(1)}%`:'—']))}
function renderPlanner(){const w=preferredWindow(state.usage),h=getCurrentCycleHistory(state.history||[],state.usage),hours=Number($('duration').value);$('durationLabel').textContent=hours===1?'1 hour':`${hours} hours`;const plan=sessionPlanner(w,h,hours);$('planUse').textContent=plan?`${plan.expectedUse.toFixed(1)}%`:'Need more pacing data';$('planRemaining').textContent=plan?`${plan.remainingAfter.toFixed(1)}%`:'—';const p=w?calculatePacing(w,h,{targetRemaining:getSettings().targetRemaining,tolerance:getSettings().paceTolerance}):null;$('planSafe').textContent=p?`${p.safePerDay.toFixed(1)}% / day`:'—';if(!plan)$('planAssessment').textContent='Insufficient data';else if(plan.expectedUse>w.remainingPercent)$('planAssessment').textContent='Too large';else if(p&&plan.expectedUse>p.safePerDay)$('planAssessment').textContent='Heavy vs daily budget';else $('planAssessment').textContent='Fits current pace'}
function renderAlerts(){const a=Array.isArray(state.alertHistory)?state.alertHistory.slice().reverse():[];renderTable($('alertTable'),['Time','Event','Message','Channels'],a.slice(0,30).map(x=>[new Date(Number(x.t)||0).toLocaleString(),x.type,x.message,Array.isArray(x.channels)?x.channels.join(', '):'']))}
function fillSettings(){const s=getSettings();$('thresholds').value=(s.thresholds||[25,10,0]).join(', ');$('predictiveAlert').checked=s.predictiveAlert!==false;$('burnAlert').checked=s.burnAlert!==false;$('unusedAlert').checked=s.unusedCapacityAlert!==false;$('unusedThreshold').value=s.unusedCapacityThreshold??50;$('unusedHours').value=s.unusedCapacityHours??24;$('resetAlert').checked=s.resetAlert!==false;$('cooldown').value=s.alertCooldownMinutes??120;$('emailEnabled').checked=!!s.emailEnabled;$('emailRelayUrl').value=s.emailRelayUrl||'';$('emailRelaySecret').value=s.emailRelaySecret||'';$('discordEnabled').checked=!!s.discordEnabled;$('discordWebhook').value=s.discordWebhook||'';$('telegramEnabled').checked=!!s.telegramEnabled;$('telegramToken').value=s.telegramBotToken||'';$('telegramChat').value=s.telegramChatId||'';$('webhookEnabled').checked=!!s.genericWebhookEnabled;$('webhook').value=s.genericWebhook||'';$('pollMinutes').value=s.pollMinutes??10;$('toolbarMode').value=s.toolbarMode||'remaining';$('overlayEnabled').checked=s.overlayEnabled!==false;$('overlayCompact').checked=s.overlayCompact!==false;$('targetRemaining').value=s.targetRemaining??0;$('paceTolerance').value=s.paceTolerance??3;$('monthlyCost').value=s.subscriptionMonthlyCost||'';$('currency').value=s.subscriptionCurrency||'USD'}
function collectSettings(){return{...getSettings(),thresholds:$('thresholds').value.split(',').map(x=>Number(x.trim())).filter(n=>Number.isFinite(n)&&n>=0&&n<=100),predictiveAlert:$('predictiveAlert').checked,burnAlert:$('burnAlert').checked,unusedCapacityAlert:$('unusedAlert').checked,unusedCapacityThreshold:Number($('unusedThreshold').value),unusedCapacityHours:Number($('unusedHours').value),resetAlert:$('resetAlert').checked,alertCooldownMinutes:Number($('cooldown').value),emailEnabled:$('emailEnabled').checked,emailRelayUrl:$('emailRelayUrl').value.trim(),emailRelaySecret:$('emailRelaySecret').value,discordEnabled:$('discordEnabled').checked,discordWebhook:$('discordWebhook').value.trim(),telegramEnabled:$('telegramEnabled').checked,telegramBotToken:$('telegramToken').value.trim(),telegramChatId:$('telegramChat').value.trim(),genericWebhookEnabled:$('webhookEnabled').checked,genericWebhook:$('webhook').value.trim(),pollMinutes:Number($('pollMinutes').value),toolbarMode:$('toolbarMode').value,overlayEnabled:$('overlayEnabled').checked,overlayCompact:$('overlayCompact').checked,targetRemaining:Number($('targetRemaining').value),paceTolerance:Number($('paceTolerance').value),subscriptionMonthlyCost:$('monthlyCost').value,subscriptionCurrency:$('currency').value}}
async function save(){const settings=collectSettings();await chrome.storage.local.set({settings});state.settings=settings;$('saveStatus').textContent='Saved';setTimeout(()=>$('saveStatus').textContent='',1500);renderAll()}
function renderDiagnostics(){const d=state.diagnostics||{};$('diagnosticText').textContent=JSON.stringify({extensionVersion:chrome.runtime.getManifest().version,lastSuccessAt:state.lastSuccessAt?new Date(state.lastSuccessAt).toISOString():null,lastError:state.lastError||null,source:d.source||null,latencyMs:d.latencyMs||null,parserVersion:d.parserVersion||null,windowsFound:d.windowsFound||0,responseShape:d.responseShape||null,historyPoints:Array.isArray(state.history)?state.history.length:0,resetEvents:Array.isArray(state.resetEvents)?state.resetEvents.length:0,normalizedUsage:state.usage||null},null,2);const holder=$('healthCards');holder.textContent='';for(const [label,value] of [['Connection',state.lastError?'Error':'OK'],['Parser',state.usage?.windows?.length?'OK':'No window'],['History',`${state.history?.length||0} samples`],['Last refresh',state.lastSuccessAt?new Date(state.lastSuccessAt).toLocaleTimeString():'Never']]){const article=document.createElement('article');article.className='stat';const span=document.createElement('span'),strong=document.createElement('b');span.textContent=label;strong.textContent=value;article.append(span,strong);holder.append(article)}}
function renderAll(){renderQuotaSummary(state.usage);renderOverview();drawChart();renderHeat();renderCycles();renderSessions();renderPlanner();renderAlerts();renderDiagnostics()}
async function load(){state=await chrome.storage.local.get(['usage','history','settings','resetEvents','alertHistory','diagnostics','lastError','lastSuccessAt']);$('version').textContent=chrome.runtime.getManifest().version;fillSettings();renderAll()}
async function refresh(){const button=$('refresh'),label=button.textContent;button.disabled=true;button.textContent='Refreshing…';try{const r=await chrome.runtime.sendMessage({type:'refresh'});if(!r?.ok)alert(r?.error||'Refresh failed');await load()}finally{button.disabled=false;button.textContent=label}}
async function requestOrigin(urlText){const url=new URL(urlText);if(url.protocol!=='https:')throw new Error('Only HTTPS integrations are supported');if(url.username||url.password)throw new Error('URLs containing embedded credentials are not supported');const origin=`${url.protocol}//${url.host}/*`;return chrome.permissions.request({origins:[origin]})}
async function grantWebhook(){try{const ok=await requestOrigin($('webhook').value.trim());alert(ok?'Permission granted.':'Permission not granted.')}catch(e){alert(e.message||'Enter a valid HTTPS webhook URL first.')}}
async function testChannel(ch){await save();const s=getSettings();const url=ch==='email'?s.emailRelayUrl:ch==='discord'?s.discordWebhook:ch==='telegram'?'https://api.telegram.org/':ch==='webhook'?s.genericWebhook:'';if(url){try{const ok=await requestOrigin(url);if(!ok){alert('Host permission was not granted.');return}}catch(e){alert(e.message);return}}const r=await chrome.runtime.sendMessage({type:'testExternal',channel:ch});alert(r?.ok?r.result:r?.error||'Test failed')}
function download(name,type,text){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function exportJson(){const d=await chrome.storage.local.get(['usage','history','resetEvents','alertHistory','settings']);const safe=structuredClone(d);if(safe.settings){delete safe.settings.emailRelayUrl;delete safe.settings.emailRelaySecret;delete safe.settings.discordWebhook;delete safe.settings.telegramBotToken;delete safe.settings.telegramChatId;delete safe.settings.genericWebhook}download(`codex-capacity-backup-${new Date().toISOString().slice(0,10)}.json`,'application/json',JSON.stringify({version:2,exportedAt:new Date().toISOString(),data:safe},null,2))}
async function exportCsv(){const rows=[['timestamp','remaining_percent','used_percent','reset_at','window_id'],...(state.history||[]).map(p=>[new Date(p.t).toISOString(),p.remaining,p.used,p.resetAt?new Date(p.resetAt*1000).toISOString():'',p.windowId])];download(`codex-capacity-history-${new Date().toISOString().slice(0,10)}.csv`,'text/csv',rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'))}
async function importJson(file){if(!file)throw new Error('Choose a backup file');if(file.size>5_000_000)throw new Error('Backup is too large');const json=JSON.parse(await file.text());if(!json?.data||typeof json.data!=='object')throw new Error('Invalid backup');const existing=(await chrome.storage.local.get('settings')).settings||{},incoming=json.data,allowed={};if(incoming.usage&&typeof incoming.usage==='object')allowed.usage=incoming.usage;if(Array.isArray(incoming.history))allowed.history=incoming.history.slice(-12000);if(Array.isArray(incoming.resetEvents))allowed.resetEvents=incoming.resetEvents.slice(-100);if(Array.isArray(incoming.alertHistory))allowed.alertHistory=incoming.alertHistory.slice(-500);if(incoming.settings&&typeof incoming.settings==='object'){const settings={...existing};for(const key of Object.keys(existing))if(Object.hasOwn(incoming.settings,key))settings[key]=incoming.settings[key];allowed.settings=settings}await chrome.storage.local.set(allowed);await load()}
async function selfTest(){const r=await chrome.runtime.sendMessage({type:'runSelfTest'});alert((r?.data?.checks||[]).map(c=>`${c.pass?'✓':'✗'} ${c.name}${c.detail?' — '+c.detail:''}`).join('\n')||r?.error||'No result')}
async function copyDiag(){const r=await chrome.runtime.sendMessage({type:'copyDiagnostics'});if(r?.ok){await navigator.clipboard.writeText(JSON.stringify(r.data,null,2));alert('Diagnostics copied.')}}
async function enableConfiguredIntegration(ch){await save();const set=getSettings();const enabled=ch==='email'?set.emailEnabled:ch==='discord'?set.discordEnabled:ch==='telegram'?set.telegramEnabled:set.genericWebhookEnabled;if(!enabled)return;const url=ch==='email'?set.emailRelayUrl:ch==='discord'?set.discordWebhook:ch==='telegram'?'https://api.telegram.org/':set.genericWebhook;if(!url){alert(`Enter the ${ch} configuration first.`);return}try{const ok=await requestOrigin(url);if(!ok)alert('Host permission was not granted.')}catch(e){alert(e.message)}}
['email','discord','telegram','webhook'].forEach(ch=>{const id=ch==='webhook'?'webhookEnabled':`${ch}Enabled`;$(id)?.addEventListener('change',()=>enableConfiguredIntegration(ch))});
$('openPrivacy').onclick=()=>chrome.tabs.create({url:chrome.runtime.getURL('privacy.html')});$('openOnboarding').onclick=()=>chrome.tabs.create({url:chrome.runtime.getURL('onboarding.html')});$('refresh').onclick=refresh;$('range').onchange=()=>{drawChart()};$('duration').oninput=renderPlanner;$('saveSettings').onclick=save;$('monthlyCost').onchange=save;$('currency').onchange=save;$('grantWebhook').onclick=grantWebhook;document.querySelectorAll('[data-test]').forEach(b=>b.onclick=()=>testChannel(b.dataset.test));$('clearAlerts').onclick=async()=>{await chrome.storage.local.set({alertHistory:[]});await load()};$('exportJson').onclick=exportJson;$('exportCsv').onclick=exportCsv;$('importJson').onchange=async e=>{try{await importJson(e.target.files[0])}catch(err){alert(err.message)}};$('clearHistory').onclick=async()=>{if(confirm('Clear stored usage history?')){await chrome.storage.local.set({history:[],resetEvents:[]});await load()}};$('resetExtension').onclick=async()=>{if(confirm('Delete all local Codex Capacity data and settings?')){await chrome.storage.local.clear();location.reload()}};$('selfTest').onclick=selfTest;$('copyDiagnostics').onclick=copyDiag;installHelpTooltips();load();window.addEventListener('resize',()=>drawChart());
